name: Test Automation WorkFlow

on:
  schedule:
    - cron: ''  # Runs daily at 6 PM UTC
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install
        working-directory: Automation-Assignment

      - name: Run Test Automation
        run: mvn test -x -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false
        working-directory: Automation-Assignment

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Test logs
          path: Automation-Assignment/logs/

      - name: Upload Screenshots as Artifacts
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: screenshots
          path: Automation-Assignment/screenshots/

      - name: Upload HTML Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: html-report
          path: Automation-Assignment/report.html

      - name: Test Execution Status
        if: always()
        run: echo "Test Execution Completed"

      - name: Copy Report to gh-pages Folder
        if: always()
        run: |
          mkdir -p public/extent-reports
          cp Automation-Assignment/report.html public/extent-reports/
          cp -R Automation-Assignment/screenshots/ public/extent-reports/screenshots/
          ls -l public/extent-reports

      - name: Deploy 🚀
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public/extent-reports/
          token: ${{ secrets.PAT4344 }}
          clean: true
